version: "3"

services:
  zap:
    build:
      context: ./zap

    command: bash -c "zap.sh -cmd -addonupdate -addoninstall fuzzdb -addoninstall help_ja_JP -addoninstall wappalyzer -addonuninstall hud -configfile /zap/wrk/options.properties -certpubdump /zap/wrk/owasp_zap_root_ca.cer && zap-webswing.sh"
    volumes:
      - ./zap:/zap/wrk/
    ports:
      - "8081:8080"
      - "8090:8090"
    depends_on:
      - ec-cube
    networks:
      - backend
      - default
    tty: true
