blank_issues_enabled: false
contact_links:
  - name: 脆弱性報告(Vulnerability Report)
    url: https://www.ec-cube.net/contact/
    about: 公式サイトのお問い合わせフォームへ(概要と再現手順を必ずご記載ください)
  - name: 開発コミュニティ(Developer Community)
    url: https://xoops.ec-cube.net/
    about: 開発者同士の相談や議論はこちら
