name: E2E test for EC-CUBE
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    paths:
      - '**'
      - '!*.md'
jobs:
  codeception:
    name: Codeception
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-18.04 ]
        php: [ 7.3 ]
        db: [ pgsql ]
        group: [ admin01, admin02, admin03, front, installer ]
        include:
          - db: pgsql
            database_url: postgres://dbuser:secret@postgres:5432/eccubedb
            database_server_version: 10
          - group: admin01
            app_env: 'codeception'
          - group: admin02
            app_env: 'codeception'
          - group: admin03
            app_env: 'codeception'
          - group: front
            app_env: 'codeception'
          - group: installer
            app_env: 'install'

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}
      - name: composer install
        run: |
          sudo composer selfupdate --1
          composer install --dev --no-interaction -o --apcu-autoloader
      - name: Start Docker container
        env:
          APP_ENV: 'codeception'
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          MAILER_URL: 'smtp://localhost:1025'
          ECCUBE_PACKAGE_API_URL: 'http://localhost:8080'
        run: docker-compose up -d

      - name: Setup to EC-CUBE
        env:
          APP_ENV: ${{ matrix.app_env }}
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
        run: |
          docker-compose exec -T ec-cube echo "APP_ENV=${APP_ENV}" > .env
          docker-compose exec -T ec-cube echo "DATABASE_URL=${DATABASE_URL}" >> .env
          docker-compose exec -T ec-cube echo "DATABASE_VERSION=${DATABASE_VERSION}" >> .env
          docker-compose exec -T ec-cube bin/console doctrine:schema:create --env=dev
          docker-compose exec -T ec-cube bin/console eccube:fixtures:load --env=dev

      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@master

      - name: Run chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          echo ">>> Started chrome-driver"
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"

      - name: Codeception
        env:
          APP_ENV: ${{ matrix.app_env }}
          DATABASE_URL: postgres://dbuser:secret@127.0.0.1:15432/eccubedb
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          MAILER_URL: 'smtp://localhost:1025'
          ECCUBE_PACKAGE_API_URL: 'http://localhost:8080'
          GROUP: ${{ matrix.group }}
          SYMFONY_DEPRECATIONS_HELPER: weak
        run: vendor/bin/codecept -vvv run acceptance --env chrome,github_action -g ${GROUP}
      - name: Upload evidence
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.group }}-evidence
          path: codeception/_output/
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.group }}-logs
          path: var/log/
